import argparse
import pickle
from pathlib import Path
from datetime import datetime

import matplotlib.pyplot as plt
import numpy as np
import qutip as qt


def load_reduced_cavity_data(data_path, case="undriven"):
    with Path(data_path).open("rb") as f:
        payload = pickle.load(f)

    # Backward compatibility:
    # old format -> top-level time_points, avg_rho_cav
    # new format -> payload["undriven"/"driven"]["time_points"/"avg_rho_cav"]
    if "time_points" in payload and "avg_rho_cav" in payload:
        time_points = np.asarray(payload["time_points"])
        avg_rho_cav = np.asarray(payload["avg_rho_cav"])
    else:
        if case not in payload:
            raise KeyError(f"Case '{case}' not found. Available keys: {list(payload.keys())}")
        time_points = np.asarray(payload[case]["time_points"])
        avg_rho_cav = np.asarray(payload[case]["avg_rho_cav"])

    if avg_rho_cav.ndim != 3 or avg_rho_cav.shape[1:] != (5, 5):
        raise ValueError("Expected avg_rho_cav with shape (n_t, 5, 5).")
    return time_points, avg_rho_cav


def load_reduced_cavity_state(data_path, case="undriven", index=None, time_ns=None):
    time_points, avg_rho_cav = load_reduced_cavity_data(data_path, case=case)

    if time_ns is not None:
        idx = int(np.argmin(np.abs(time_points - time_ns)))
    elif index is not None:
        idx = int(index)
    else:
        idx = -1  # default: final time

    if idx < -len(time_points) or idx >= len(time_points):
        raise IndexError(f"Index {idx} out of range for {len(time_points)} time points.")

    rho_cav = qt.Qobj(avg_rho_cav[idx], dims=[[5], [5]])
    return rho_cav, float(time_points[idx]), idx


def plot_wigner(rho_cav, t_value, xlim=6.0, grid=201, save_path=None, dpi=200):
    x = np.linspace(-xlim, xlim, grid)
    W = qt.wigner(rho_cav, x, x)

    fig, ax = plt.subplots(figsize=(6, 5))
    levels = np.linspace(W.min(), W.max(), 120)
    cf = ax.contourf(x, x, W, levels=levels, cmap="RdBu_r")
    ax.contour(x, x, W, levels=[0], colors="k", linewidths=0.8)
    ax.set_xlabel("q")
    ax.set_ylabel("p")
    ax.set_title(f"Cavity Wigner function (transmon traced out), t={t_value:.2f} ns")
    ax.set_aspect("equal")
    fig.colorbar(cf, ax=ax, label="W(q,p)")
    plt.tight_layout()
    if save_path is not None:
        out = Path(save_path)
        out.parent.mkdir(parents=True, exist_ok=True)
        fig.savefig(out, dpi=dpi, bbox_inches="tight")
        print(f"Saved figure to: {out.resolve()}")
    plt.show()


def plot_wigner_10points(avg_rho_cav, time_points, xlim=6.0, grid=201, save_path=None, dpi=200):
    n_t = len(time_points)
    if n_t == 0:
        raise ValueError("No time points found in input data.")

    n_plot = min(10, n_t)
    if n_t <= 10:
        plot_indices = np.arange(n_t, dtype=int)
    else:
        plot_indices = np.linspace(0, n_t - 1, n_plot, dtype=int)

    x = np.linspace(-xlim, xlim, grid)
    w_list = []
    for idx in plot_indices:
        rho_cav = qt.Qobj(avg_rho_cav[idx], dims=[[5], [5]])
        w_list.append(qt.wigner(rho_cav, x, x))

    wmin = min(np.min(w) for w in w_list)
    wmax = max(np.max(w) for w in w_list)
    levels = np.linspace(wmin, wmax, 120)

    fig, axes = plt.subplots(2, 5, figsize=(18, 7), constrained_layout=True)
    axes = axes.ravel()
    cf = None
    for ax, idx, W in zip(axes, plot_indices, w_list):
        cf = ax.contourf(x, x, W, levels=levels, cmap="RdBu_r")
        ax.contour(x, x, W, levels=[0], colors="k", linewidths=0.6)
        ax.set_title(f"t={time_points[idx]:.2f} ns")
        ax.set_xlabel("q")
        ax.set_ylabel("p")
        ax.set_aspect("equal")

    # In case n_t < 10, hide unused axes.
    for ax in axes[len(plot_indices):]:
        ax.axis("off")

    if cf is not None:
        fig.colorbar(cf, ax=axes.tolist(), label="W(q,p)", shrink=0.9)
    fig.suptitle("Cavity Wigner function (transmon traced out) at 10 time points")

    if save_path is not None:
        out = Path(save_path)
        out.parent.mkdir(parents=True, exist_ok=True)
        fig.savefig(out, dpi=dpi, bbox_inches="tight")
        print(f"Saved figure to: {out.resolve()}")
    plt.show()


def main():
    parser = argparse.ArgumentParser(
        description="Plot cavity reduced Wigner function from averaged density-matrix data."
    )
    parser.add_argument(
        "--data",
        type=str,
        default="avg_density_matrix_over_time_undriven_driven.pkl",
        help="Pickle file generated by average_density_matrix_simulation.py",
    )
    parser.add_argument(
        "--case",
        type=str,
        choices=["undriven", "driven"],
        default="undriven",
        help="Which simulation case to plot for new-format files.",
    )
    parser.add_argument(
        "--index",
        type=int,
        default=None,
        help="Time index to plot (default: final time).",
    )
    parser.add_argument(
        "--time-ns",
        type=float,
        default=None,
        help="Physical time in ns (plots nearest point). Overrides --index.",
    )
    parser.add_argument("--xlim", type=float, default=6.0, help="Wigner axis limit.")
    parser.add_argument("--grid", type=int, default=201, help="Wigner grid size.")
    parser.add_argument(
        "--single",
        action="store_true",
        help="Plot a single time point (use --index or --time-ns). Default is 10 points in one PNG.",
    )
    parser.add_argument(
        "--save-path",
        type=str,
        default=None,
        help="Optional path to save the figure. Default: binonmial_code folder with auto filename.",
    )
    parser.add_argument("--dpi", type=int, default=200, help="DPI for saved figure.")
    args = parser.parse_args()

    if args.save_path is None:
        mode = "single" if args.single else "10points"
        default_name = f"cavity_wigner_{mode}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.png"
        save_path = Path(__file__).resolve().parent / default_name
    else:
        save_path = Path(args.save_path)

    if args.single:
        rho_cav, t_value, idx = load_reduced_cavity_state(
            data_path=args.data, case=args.case, index=args.index, time_ns=args.time_ns
        )
        print(
            f"Plotting single ({args.case}) index={idx}, time={t_value:.4f} ns "
            f"from {Path(args.data).resolve()}"
        )
        plot_wigner(
            rho_cav,
            t_value=t_value,
            xlim=args.xlim,
            grid=args.grid,
            save_path=save_path,
            dpi=args.dpi,
        )
    else:
        time_points, avg_rho_cav = load_reduced_cavity_data(args.data, case=args.case)
        print(f"Plotting 10-point panel ({args.case}) from {Path(args.data).resolve()}")
        plot_wigner_10points(
            avg_rho_cav=avg_rho_cav,
            time_points=time_points,
            xlim=args.xlim,
            grid=args.grid,
            save_path=save_path,
            dpi=args.dpi,
        )


if __name__ == "__main__":
    main()
